# arch/arm/mach-s3c2442/Makefile
#
# Copyright 2007 Simtec Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_CPU_S3C2442)	+= s3c2442.o
obj-$(CONFIG_CPU_S3C2442)	+= clock.o

obj-$(CONFIG_MACH_NEO1973_GTA02) += mach-gta02.o \
	gta02-pm-bt.o \
	gta02-pm-gps.o \
	gta02-pm-gsm.o \
	gta02-pm-wlan.o \
	gta02-fiq.o
# Machine support

